"""
SatyaVault Streamlit MVP
------------------------
This app demonstrates immutable digital evidence tracking for GovTech forensics.

Design goals:
1) Keep blockchain writes signed by MetaMask in-browser.
2) Keep file bytes off-chain by uploading only to IPFS.
3) Store only integrity-critical metadata on chain.
4) Provide a tamper demo for judge-facing proof.
"""

import hashlib
import json
import os
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

import requests
import streamlit as st
from dotenv import load_dotenv
from web3 import Web3
from web3.contract import Contract

# Load environment values from local .env if present.
load_dotenv()

# -----------------------------
# Global app configuration
# -----------------------------
st.set_page_config(
    page_title="SatyaVault | Digital Evidence Integrity",
    page_icon="SV",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Theme colors chosen to feel like a GovTech command dashboard.
CUSTOM_CSS = """
<style>
:root {
    --saffron: #ff9933;
    --india-green: #138808;
    --navy: #0f2742;
    --panel: #f6f9fc;
    --ink: #0b1c2c;
    --muted: #5f6b7a;
}

.stApp {
    background: radial-gradient(circle at top right, rgba(255,153,51,0.18), transparent 32%),
                radial-gradient(circle at bottom left, rgba(19,136,8,0.16), transparent 36%),
                linear-gradient(160deg, #eef3f8 0%, #f9fbfd 100%);
}

.block-container {
    padding-top: 1.2rem;
}

.hero {
    border-left: 8px solid var(--saffron);
    background: white;
    border-radius: 12px;
    padding: 1rem 1.2rem;
    box-shadow: 0 8px 24px rgba(15, 39, 66, 0.08);
}

.metric-card {
    background: white;
    border-radius: 12px;
    padding: 0.9rem;
    border: 1px solid #dce5f0;
}

.timeline-wrap {
    margin-top: 8px;
}

.timeline-item {
    border-left: 4px solid var(--navy);
    margin-left: 6px;
    padding: 0.8rem 0.9rem;
    margin-bottom: 0.7rem;
    background: white;
    border-radius: 0 10px 10px 0;
    box-shadow: 0 4px 12px rgba(11, 28, 44, 0.06);
}

.status-ok {
    color: #0b7d3e;
    font-weight: 700;
}

.status-bad {
    color: #b91c1c;
    font-weight: 700;
}

.small-muted {
    color: var(--muted);
    font-size: 0.9rem;
}
</style>
"""
st.markdown(CUSTOM_CSS, unsafe_allow_html=True)


# -----------------------------
# Helper functions
# -----------------------------
def compute_sha256(file_bytes: bytes) -> str:
    """Return lowercase SHA-256 hex digest for uploaded file bytes."""
    return hashlib.sha256(file_bytes).hexdigest()


def load_contract_abi() -> List[Dict[str, Any]]:
    """
    Read ABI generated by Hardhat compile step.
    We keep this dynamic to avoid duplicate ABI files.
    """
    artifact_path = "artifacts/contracts/SatyaVault.sol/SatyaVault.json"
    if not os.path.exists(artifact_path):
        raise FileNotFoundError(
            "Contract artifact not found. Run `npx hardhat compile` first."
        )
    with open(artifact_path, "r", encoding="utf-8") as f:
        artifact = json.load(f)
    return artifact["abi"]


def get_web3() -> Optional[Web3]:
    """Create a read provider for Polygon Amoy; return None if config missing."""
    rpc_url = os.getenv("AMOY_RPC_URL", "").strip()
    if not rpc_url:
        return None
    web3 = Web3(Web3.HTTPProvider(rpc_url, request_kwargs={"timeout": 30}))
    return web3 if web3.is_connected() else None


def get_contract(web3: Web3) -> Contract:
    """Instantiate SatyaVault contract from env address and compiled ABI."""
    contract_address = os.getenv("SATYAVAULT_CONTRACT_ADDRESS", "").strip()
    if not contract_address:
        raise ValueError("SATYAVAULT_CONTRACT_ADDRESS is missing in .env")
    abi = load_contract_abi()
    return web3.eth.contract(address=Web3.to_checksum_address(contract_address), abi=abi)


def upload_to_ipfs_pinata(file_bytes: bytes, file_name: str) -> Tuple[str, str]:
    """
    Upload bytes to IPFS via Pinata and return:
    1) ipfs:// CID URI (chain storage)
    2) gateway URL (UI convenience)
    """
    pinata_jwt = os.getenv("PINATA_JWT", "").strip()
    gateway_base = os.getenv("PINATA_GATEWAY_URL", "https://gateway.pinata.cloud/ipfs/")

    if not pinata_jwt:
        raise ValueError("PINATA_JWT is missing in .env")

    url = "https://api.pinata.cloud/pinning/pinFileToIPFS"
    headers = {"Authorization": f"Bearer {pinata_jwt}"}
    files = {"file": (file_name, file_bytes)}

    # Keep metadata explicit to make explorer browsing cleaner.
    metadata = {"name": f"SatyaVault-{file_name}"}
    response = requests.post(
        url,
        headers=headers,
        files=files,
        data={"pinataMetadata": json.dumps(metadata)},
        timeout=90,
    )
    response.raise_for_status()
    cid = response.json().get("IpfsHash")
    if not cid:
        raise ValueError("Pinata response missing IpfsHash")

    ipfs_uri = f"ipfs://{cid}"
    gateway_url = f"{gateway_base.rstrip('/')}/{cid}"
    return ipfs_uri, gateway_url


def hex_to_bytes32(hex_digest: str) -> str:
    """Ensure hash string is converted to 0x-prefixed bytes32 hex."""
    cleaned = hex_digest.lower().replace("0x", "")
    if len(cleaned) != 64:
        raise ValueError("SHA-256 hash must be exactly 32 bytes (64 hex chars)")
    return f"0x{cleaned}"


def fetch_evidence(contract: Contract, evidence_id: int) -> Optional[Dict[str, Any]]:
    """Read evidence details from chain; return None if call fails."""
    try:
        item = contract.functions.getEvidence(evidence_id).call()
        return {
            "evidenceId": item[0],
            "fileHash": item[1].hex() if hasattr(item[1], "hex") else str(item[1]),
            "ipfsUri": item[2],
            "caseId": item[3],
            "investigatorId": item[4],
            "createdAt": item[5],
            "createdBy": item[6],
            "exists": item[7],
        }
    except Exception:
        return None


def fetch_custody_history(contract: Contract, evidence_id: int) -> List[Dict[str, Any]]:
    """Read full chain-of-custody timeline."""
    try:
        rows = contract.functions.getCustodyHistory(evidence_id).call()
        parsed = []
        for row in rows:
            parsed.append(
                {
                    "fromActor": row[0],
                    "toActor": row[1],
                    "fromOrg": row[2],
                    "toOrg": row[3],
                    "action": row[4],
                    "notes": row[5],
                    "timestamp": row[6],
                }
            )
        return parsed
    except Exception:
        return []


def render_timeline(history: List[Dict[str, Any]]) -> None:
    """Render vertical timeline cards for custody chain."""
    if not history:
        st.info("No custody events yet for this evidence.")
        return

    st.markdown('<div class="timeline-wrap">', unsafe_allow_html=True)
    for event in history:
        ts = datetime.utcfromtimestamp(event["timestamp"]).strftime("%d %b %Y, %H:%M UTC")
        st.markdown(
            f"""
            <div class="timeline-item">
                <div><strong>{event['action']}</strong> | {ts}</div>
                <div class="small-muted">{event['fromOrg']} -> {event['toOrg']}</div>
                <div class="small-muted">From: {event['fromActor']}</div>
                <div class="small-muted">To: {event['toActor']}</div>
                <div>{event['notes']}</div>
            </div>
            """,
            unsafe_allow_html=True,
        )
    st.markdown("</div>", unsafe_allow_html=True)


def metamask_write_widget(mode: str, payload: Dict[str, Any]) -> None:
    """
    Render a tiny in-app MetaMask transaction widget.

    Why this approach:
    - Streamlit handles Python + IPFS + read calls.
    - Wallet signing must happen in browser to avoid private keys on server.
    """
    contract_address = os.getenv("SATYAVAULT_CONTRACT_ADDRESS", "")
    if not contract_address:
        st.warning("Set SATYAVAULT_CONTRACT_ADDRESS in .env to enable MetaMask writes.")
        return

    abi = load_contract_abi()
    expected_chain_id_hex = "0x13882"  # 80002 in hex (Polygon Amoy)

    # JSON encode dynamic payload to avoid JS syntax issues.
    payload_json = json.dumps(payload)
    abi_json = json.dumps(abi)

    html = f"""
    <div style="padding:10px;border:1px solid #d6e1ef;border-radius:10px;background:#fff;">
      <h4 style="margin:0 0 8px 0;color:#0f2742;">MetaMask Transaction Signer</h4>
      <p style="margin:0 0 8px 0;font-size:13px;color:#4b5a6b;">This signs the transaction with your active MetaMask account. No private key is stored in Python.</p>
      <button id="connectBtn" style="padding:7px 12px;">Connect Wallet</button>
      <button id="sendBtn" style="padding:7px 12px;margin-left:8px;">Send Transaction</button>
      <pre id="log" style="margin-top:10px;background:#f7fafc;padding:8px;border-radius:8px;white-space:pre-wrap;"></pre>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/ethers@5.7.2/dist/ethers.umd.min.js"></script>
    <script>
      const logEl = document.getElementById("log");
      const payload = {payload_json};
      const mode = {json.dumps(mode)};
      const expectedChainId = {json.dumps(expected_chain_id_hex)};

      function log(msg) {{
        logEl.textContent += msg + "\\n";
      }}

      async function ensureWallet() {{
        if (!window.ethereum) {{
          throw new Error("MetaMask not detected in this browser. Open Streamlit in a browser with MetaMask extension.");
        }}
        await window.ethereum.request({{ method: "eth_requestAccounts" }});
        const provider = new ethers.providers.Web3Provider(window.ethereum);
        const network = await provider.getNetwork();
        const currentChainHex = "0x" + network.chainId.toString(16);
        if (currentChainHex.toLowerCase() !== expectedChainId.toLowerCase()) {{
          throw new Error(`Wrong network. Switch to Polygon Amoy (chainId 80002). Current chainId: ${{network.chainId}}`);
        }}
        const signer = provider.getSigner();
        return {{ provider, signer }};
      }}

      document.getElementById("connectBtn").onclick = async () => {{
        try {{
          const {{ signer }} = await ensureWallet();
          const addr = await signer.getAddress();
          log("Connected: " + addr);
        }} catch (err) {{
          log("Error: " + err.message);
        }}
      }};

      document.getElementById("sendBtn").onclick = async () => {{
        try {{
          const {{ signer }} = await ensureWallet();
          const abi = {abi_json};
          const contract = new ethers.Contract({json.dumps(contract_address)}, abi, signer);

          let tx;
          if (mode === "register") {{
            tx = await contract.registerEvidence(
              payload.fileHash,
              payload.ipfsUri,
              payload.caseId,
              payload.investigatorId,
              payload.initialOrg
            );
          }} else if (mode === "transfer") {{
            tx = await contract.transferCustody(
              payload.evidenceId,
              payload.toActor,
              payload.fromOrg,
              payload.toOrg,
              payload.action,
              payload.notes
            );
          }} else {{
            throw new Error("Unsupported mode");
          }}

          log("Tx sent: " + tx.hash);
          const receipt = await tx.wait();
          log("Confirmed in block: " + receipt.blockNumber);
        }} catch (err) {{
          log("Error: " + (err?.message || err));
        }}
      }};
    </script>
    """

    st.components.v1.html(html, height=290)


# -----------------------------
# Sidebar and status
# -----------------------------
st.sidebar.title("SatyaVault Control Panel")
st.sidebar.caption("Blockchain India Challenge | Digital Forensics")

rpc_url = os.getenv("AMOY_RPC_URL", "")
contract_addr = os.getenv("SATYAVAULT_CONTRACT_ADDRESS", "")
pinata_ok = bool(os.getenv("PINATA_JWT", "").strip())

st.sidebar.markdown("### Environment Health")
st.sidebar.write(f"RPC Configured: {'Yes' if rpc_url else 'No'}")
st.sidebar.write(f"Contract Address: {'Yes' if contract_addr else 'No'}")
st.sidebar.write(f"Pinata Configured: {'Yes' if pinata_ok else 'No'}")

web3 = get_web3()
if web3:
    st.sidebar.success("Amoy RPC connected")
else:
    st.sidebar.error("Amoy RPC not connected")

contract: Optional[Contract] = None
if web3 and contract_addr:
    try:
        contract = get_contract(web3)
    except Exception as err:
        st.sidebar.error(f"Contract init failed: {err}")


# -----------------------------
# Header
# -----------------------------
st.markdown(
    """
    <div class="hero">
      <h2 style="margin:0;color:#0f2742;">SatyaVault: Immutable Chain-of-Custody for Digital Evidence</h2>
      <div class="small-muted">Mock agencies: Cyber Crime Cell -> Forensic Science Laboratory -> e-Courts</div>
    </div>
    """,
    unsafe_allow_html=True,
)

if contract:
    try:
        total_evidence = contract.functions.evidenceCount().call()
    except Exception:
        total_evidence = 0
else:
    total_evidence = 0

c1, c2, c3 = st.columns(3)
c1.markdown(f"<div class='metric-card'><b>Evidence Records</b><br>{total_evidence}</div>", unsafe_allow_html=True)
c2.markdown(
    "<div class='metric-card'><b>Network</b><br>Polygon Amoy (80002)</div>",
    unsafe_allow_html=True,
)
c3.markdown(
    "<div class='metric-card'><b>Integrity Engine</b><br>SHA-256 + Smart Contract Logs</div>",
    unsafe_allow_html=True,
)

st.markdown("")

# -----------------------------
# Main tabs
# -----------------------------
submit_tab, transfer_tab, verify_tab, demo_tab = st.tabs(
    ["1) Submit Evidence", "2) Transfer Custody", "3) Verify Integrity", "4) Tamper Demo"]
)


with submit_tab:
    st.subheader("Evidence Submission")
    st.caption("Upload file -> hash locally -> upload to IPFS -> sign blockchain transaction with MetaMask")

    uploaded = st.file_uploader("Upload Evidence (Image/PDF)", type=["png", "jpg", "jpeg", "pdf"], key="submit_file")

    if uploaded:
        file_bytes = uploaded.getvalue()
        digest = compute_sha256(file_bytes)

        st.code(f"Local SHA-256: {digest}")

        case_id = st.text_input("Case ID", value="IN-CCC-2026-001")
        investigator_id = st.text_input("Investigator ID", value="INV-SATYA-17")
        initial_org = st.selectbox(
            "Initial Holding Agency",
            ["Cyber Crime Cell", "State Police Digital Unit", "CBI Digital Forensics Wing"],
        )

        if st.button("Upload to IPFS", type="primary"):
            try:
                ipfs_uri, gateway_url = upload_to_ipfs_pinata(file_bytes, uploaded.name)
                st.session_state["latest_ipfs_uri"] = ipfs_uri
                st.session_state["latest_gateway_url"] = gateway_url
                st.session_state["latest_hash"] = digest
                st.success("File uploaded to IPFS")
                st.write(f"IPFS URI: `{ipfs_uri}`")
                st.write(f"Gateway URL: {gateway_url}")
            except Exception as err:
                st.error(f"IPFS upload failed: {err}")

        if st.session_state.get("latest_ipfs_uri") and st.session_state.get("latest_hash"):
            st.info("Step 2: Use MetaMask below to record hash + metadata on-chain")
            payload = {
                "fileHash": hex_to_bytes32(st.session_state["latest_hash"]),
                "ipfsUri": st.session_state["latest_ipfs_uri"],
                "caseId": case_id,
                "investigatorId": investigator_id,
                "initialOrg": initial_org,
            }
            metamask_write_widget("register", payload)


with transfer_tab:
    st.subheader("Chain-of-Custody Logging")
    st.caption("Current custodian signs transfer to next agency wallet")

    evidence_id = st.number_input("Evidence ID", min_value=1, step=1, value=1)
    to_actor = st.text_input("Next Custodian Wallet Address", value="0x000000000000000000000000000000000000dEaD")
    from_org = st.selectbox("From Agency", ["Cyber Crime Cell", "Forensic Science Laboratory", "e-Courts"], index=0)
    to_org = st.selectbox("To Agency", ["Forensic Science Laboratory", "e-Courts", "Evidence Locker"], index=0)
    action = st.selectbox("Transfer Action", ["SEALED_AND_SENT", "LAB_RECEIVED", "SUBMITTED_TO_COURT"])
    notes = st.text_area("Transfer Notes", value="Sealed drive packet handed over with chain form signed.")

    st.info("Use MetaMask signer to create an immutable transfer record")
    transfer_payload = {
        "evidenceId": int(evidence_id),
        "toActor": to_actor,
        "fromOrg": from_org,
        "toOrg": to_org,
        "action": action,
        "notes": notes,
    }
    metamask_write_widget("transfer", transfer_payload)

    if contract:
        history = fetch_custody_history(contract, int(evidence_id))
        st.markdown("### Custody Timeline")
        render_timeline(history)


with verify_tab:
    st.subheader("Public Integrity Verification")
    st.caption("Anyone can verify if a file matches the immutable on-chain hash")

    evidence_id = st.number_input("Evidence ID to Verify", min_value=1, step=1, value=1, key="verify_id")
    verify_file = st.file_uploader("Upload file for verification", type=["png", "jpg", "jpeg", "pdf"], key="verify_file")

    if contract and verify_file:
        local_bytes = verify_file.getvalue()
        local_hash = compute_sha256(local_bytes)

        try:
            result = contract.functions.verifyIntegrity(int(evidence_id), bytes.fromhex(local_hash)).call()
            if result:
                st.markdown("<p class='status-ok'>Tamper-Proof: Hash matches on-chain record.</p>", unsafe_allow_html=True)
            else:
                st.markdown("<p class='status-bad'>Tampered: Hash mismatch detected.</p>", unsafe_allow_html=True)

            evidence = fetch_evidence(contract, int(evidence_id))
            if evidence:
                st.write(f"On-chain Hash: `{evidence['fileHash']}`")
                st.write(f"Local Hash: `{local_hash}`")
                st.write(f"IPFS URI: `{evidence['ipfsUri']}`")
                st.write(f"Case ID: `{evidence['caseId']}`")
                st.write(f"Investigator ID: `{evidence['investigatorId']}`")
        except Exception as err:
            st.error(f"Verification failed: {err}")
    elif verify_file and not contract:
        st.warning("Contract is not connected. Configure .env and retry.")


with demo_tab:
    st.subheader("Judge Demo: Intentional Tampering")
    st.caption("This creates a single-byte mutation to prove real-time mismatch detection")

    demo_evidence_id = st.number_input("Evidence ID", min_value=1, step=1, value=1, key="demo_evidence_id")
    demo_file = st.file_uploader("Upload original evidence file", type=["png", "jpg", "jpeg", "pdf"], key="demo_file")

    if demo_file and contract:
        original = demo_file.getvalue()
        original_hash = compute_sha256(original)

        # One-byte mutation is enough to completely change SHA-256 output.
        tampered = bytearray(original)
        if tampered:
            tampered[0] = (tampered[0] + 1) % 256
        tampered_hash = compute_sha256(bytes(tampered))

        c_left, c_right = st.columns(2)

        with c_left:
            st.markdown("#### Original File Check")
            try:
                ok = contract.functions.verifyIntegrity(int(demo_evidence_id), bytes.fromhex(original_hash)).call()
                status_html = "<p class='status-ok'>MATCHED</p>" if ok else "<p class='status-bad'>MISMATCH</p>"
                st.markdown(status_html, unsafe_allow_html=True)
                st.code(f"Original Hash: {original_hash}")
            except Exception as err:
                st.error(f"Original check failed: {err}")

        with c_right:
            st.markdown("#### Tampered File Check")
            try:
                ok2 = contract.functions.verifyIntegrity(int(demo_evidence_id), bytes.fromhex(tampered_hash)).call()
                status_html2 = "<p class='status-ok'>MATCHED</p>" if ok2 else "<p class='status-bad'>TAMPER DETECTED</p>"
                st.markdown(status_html2, unsafe_allow_html=True)
                st.code(f"Tampered Hash: {tampered_hash}")
            except Exception as err:
                st.error(f"Tampered check failed: {err}")

        st.markdown(
            """
            <div class="small-muted">
            Demo tip: In live pitch, first show MATCHED for original, then switch to tampered check result.
            This visual contrast is usually the strongest integrity proof for judges.
            </div>
            """,
            unsafe_allow_html=True,
        )

    elif demo_file and not contract:
        st.warning("Contract connection missing. Please configure RPC + contract address first.")

st.markdown("---")
st.caption(
    "Resilience note: the UI surfaces readable errors for wallet/network/IPFS issues to keep live demos stable."
)
